name: Generate Docs Sidebar (using docsify-cli)

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'        # run when ANY file in docs/ changes …
      - '!docs/_sidebar.md'   # … except when only _sidebar.md changes
  workflow_dispatch:      # allow manual runs

jobs:
  generate-sidebar:
    runs-on: ubuntu-latest

    permissions:
      contents: write     # we are going to git-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ←-- we are going to push back to the same branch

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install docsify-cli locally
        run: npm i docsify-cli@latest

      - name: Generate sidebar
        # This command is FIXED in point 2 below.
        run: npx docsify-sidebar-generator -d docs -o docs/_sidebar.md

      - name: Commit & push sidebar (if it changed)
        run: |
          if ! git diff --quiet docs/_sidebar.md ; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/_sidebar.md
            git commit -m "docs: auto-generate sidebar [skip ci]"
            git push
          else
            echo "Nothing changed – skip commit."
          fi
