name: Generate Docs Sidebar (using docsify-cli)

on:
  push:
    branches:
      - main # Or your primary branch if different (e.g., master)
    paths:
      - 'docs/**'         # Trigger on any change within the docs folder
      - '!docs/_sidebar.md' # IMPORTANT: Prevent loop if action commits this file
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  generate-sidebar:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or any LTS version compatible with docsify-cli

      - name: Install docsify-cli globally
        # As per the documentation you provided: npm i docsify-cli -g
        run: npm install -g docsify-cli

      - name: Verify docsify-cli version
        # This will tell us which version was installed
        run: docsify --version

      - name: Show help for 'generate' command
        # This step is important to see the exact options for the installed version
        run: docsify generate --help

      - name: Generate sidebar
        # Using the command structure from YOUR latest documentation (NO --overwrite)
        run: docsify generate ./docs --sidebar _sidebar.md

      - name: Commit and push if sidebar changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Stage the potentially changed sidebar
          git add docs/_sidebar.md
          # Check if there are staged changes for the sidebar
          if ! git diff --staged --quiet docs/_sidebar.md; then
            git commit -m "docs: auto-generate sidebar via docsify-cli [skip ci]"
            git push
          else
            echo "No changes to docs/_sidebar.md, nothing to commit."
          fi
