name: Generate Docs Sidebar (using docsify-cli)

on:
  push:
    branches:
      - main # Or your primary branch if different (e.g., master)
    paths:
      - 'docs/**'         # Trigger on any change within the docs folder
      - '!docs/_sidebar.md' # IMPORTANT: Prevent loop if action commits this file
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  generate-sidebar:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or any LTS version compatible with docsify-cli

      - name: Install docsify-cli LOCALLY
        # This installs docsify-cli@latest into the local node_modules directory (NO -g FLAG)
        run: npm install docsify-cli@latest

      - name: Verify version of LOCALLY installed docsify-cli (using npx)
        # npx should pick up ./node_modules/.bin/docsify
        # This step will show us which version is being detected.
        # It should be 4.4.0 or higher for --overwrite or -o to be supported.
        run: npx docsify --version

      - name: Show help for 'generate' command (using npx)
        # This step will show us if the detected docsify version lists --overwrite / -o as an option.
        # THIS IS CRUCIAL.
        run: npx docsify generate --help

      - name: Generate sidebar (using npx with locally installed docsify-cli)
        # npx will find and use the docsify-cli installed in node_modules/.bin
        # Using the shorthand -o as per your suggestion and the documentation.
        # You can also try --overwrite here if -o fails, but the help output above will guide us.
        run: npx docsify generate ./docs --sidebar _sidebar.md -o

      - name: Commit and push if sidebar changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Stage the potentially changed sidebar
          git add docs/_sidebar.md
          # Check if there are staged changes for the sidebar
          if ! git diff --staged --quiet docs/_sidebar.md; then
            git commit -m "docs: auto-generate sidebar via docsify-cli [skip ci]"
            git push
          else
            echo "No changes to docs/_sidebar.md, nothing to commit."
          fi
