name: Generate Docs Sidebar (using docsify-cli)

on:
  push:
    branches:
      - main # Or your primary branch if different (e.g., master)
    paths:
      - 'docs/**'         # Trigger on any change within the docs folder
      - '!docs/_sidebar.md' # IMPORTANT: Prevent loop if action commits this file
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  generate-sidebar:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or any LTS version compatible with docsify-cli

      - name: Install docsify-cli
        run: npm install -g docsify-cli

      - name: Generate sidebar
        # This command targets your 'docs' directory.
        # --sidebar _sidebar.md ensures it generates/updates docs/_sidebar.md
        # --overwrite allows it to update an existing file.
        run: docsify generate ./docs --sidebar _sidebar.md --overwrite

      - name: Commit and push if sidebar changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Stage the potentially changed sidebar
          git add docs/_sidebar.md
          # Check if there are staged changes for the sidebar
          if ! git diff --staged --quiet docs/_sidebar.md; then
            git commit -m "docs: auto-generate sidebar via docsify-cli [skip ci]"
            git push
          else
            echo "No changes to docs/_sidebar.md, nothing to commit."
          fi
